parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"
  - import

extends:
  - plugin:@typescript-eslint/recommended
  - plugin:react-hooks/recommended
  - prettier
  - prettier/@typescript-eslint
