version: "3.7"

services:
  elasticsearch:
    image: elasticsearch:7.9.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      discovery.type: "single-node"

  nextjs:
    image: node:10
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    environment:
      ELASTICSEARCH_ENDPOINT: http://elasticsearch:9200
    command: yarn dev
