name: Reindex BoardGameGeek

on:
  workflow_dispatch:
    inputs:
      options:
        description: "Additional Ingest Options"

  schedule:
    - cron: "0 7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Cache/restore Python dependencies
        uses: actions/cache@v2
        with:
          path: ./env
          key: ${{ runner.os }}-build-python-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-build-python-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install Python dependencies
        run: |
          python3 -m venv env
          . env/bin/activate
          pip install -r requirements.txt

      - name: Run reindex
        env:
          ELASTICSEARCH_ENDPOINT: ${{ secrets.ELASTICSEARCH_ENDPOINT }}
        run: |
          . env/bin/activate
          python ingest.py run \
            --connection-from-env \
            --max-rank 9700 \
            ${{ github.event.inputs.options }}

      # Redeploy to bust Vercel cache.
      - uses: amondnet/vercel-action@v19
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: "--prod"
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
